<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Itech.Querying</PackageId>
    <Description>Reusable dynamic-query helpers for Itech APIs.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>itech;querying;dynamic-query;domainrelay</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DomainRelay.Mapping.Expressions" />
  </ItemGroup>

</Project>
